global:
  mappings:
    # format is src -> dst
    # src is relative to .dotfiles directory
    # dst is the actual file that is used in the system
    # symlink is usually the other way
    - .config/ghostty -> ~/.config/ghostty
    - .config/alacritty -> ~/.config/alacritty

  templates:
    .config/ghostty/config:
      font_family: "Fantasque Sans Mono"
      font_size: 12

penguin:
  excluded:
    - .config/alacritty -> ~/.config/alacritty

  templates:
    .config/ghostty/config:
      font_family: ""
      font_size: 10
