#!/bin/sh

_randpick()
{
    echo "$@" | tr ' ' '\n' | awk 'BEGIN{srand()} {a[NR]=$0} END{print a[int(rand()*NR)+1]}'
}

randname()
{
    local adj noun ts
    adj=$(_randpick swift brave calm dark eager fierce gentle hidden keen lucid noble prime quiet rapid sharp vivid warm bold crisp deft)
    noun=$(_randpick fox wolf hawk bear lynx crow pike reef sage tide vale wren arch bolt cove dune fern glen jade knot)
    ts=$(printf '%x' "$(date +%s)")

    echo "${adj}-${noun}-${ts}"
}
