import = [
    "~/.config/alacritty/custom.toml"
]

[cursor]
vi_mode_style = "Beam"

[cursor.style]
shape = "Block"

[font.normal]
family = "Fantasque Sans Mono"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
